---
- name: Deploy apps
  hosts: do
  remote_user: deploy
  become: yes

  tasks:
    - name: Add .service file
      template:
        src: templates/node-app.service
        dest: /etc/systemd/system/node-app.service

    - name: Start service
      systemd:
        state: restarted
        name: node-app
        daemon_reload: yes